// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATdjQKJZoC4LWU3kfWHo-itlDevvSTHh0',
    appId: '1:77910416478:web:ce60484f1023fdb02328cf',
    messagingSenderId: '77910416478',
    projectId: 'villa-a2a74',
    authDomain: 'villa-a2a74.firebaseapp.com',
    storageBucket: 'villa-a2a74.appspot.com',
    measurementId: 'G-DZ7M078D4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4RYb2lUzhNpIcisfPeln7iD9McFmaWdk',
    appId: '1:77910416478:android:1636961ead94a94d2328cf',
    messagingSenderId: '77910416478',
    projectId: 'villa-a2a74',
    storageBucket: 'villa-a2a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEbtMvV0HSTDsnyO2UHnIKWIy3qtw2qGI',
    appId: '1:77910416478:ios:7da8602c8487f5922328cf',
    messagingSenderId: '77910416478',
    projectId: 'villa-a2a74',
    storageBucket: 'villa-a2a74.appspot.com',
    iosBundleId: 'com.example.loginForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEbtMvV0HSTDsnyO2UHnIKWIy3qtw2qGI',
    appId: '1:77910416478:ios:7da8602c8487f5922328cf',
    messagingSenderId: '77910416478',
    projectId: 'villa-a2a74',
    storageBucket: 'villa-a2a74.appspot.com',
    iosBundleId: 'com.example.loginForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATdjQKJZoC4LWU3kfWHo-itlDevvSTHh0',
    appId: '1:77910416478:web:358ac2e20e3c11812328cf',
    messagingSenderId: '77910416478',
    projectId: 'villa-a2a74',
    authDomain: 'villa-a2a74.firebaseapp.com',
    storageBucket: 'villa-a2a74.appspot.com',
    measurementId: 'G-LC3NZERJY6',
  );
}
